Repository GlueOps/backup-tools, pull requests merged in 2024-10, with the labels that each got.

#50 Update and rename image.yaml to container_image.yaml
  .github/workflows/container_image.yaml
  .github/workflows/image.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#59 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#55 chore(deps): update ubuntu:22.04 docker digest to 58b8789
  Dockerfile
Labels: include-in-release-notes, patch, auto-update, dependencies
